package net.softavis.healthhub.ui

import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.Button
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.collectAsState
import androidx.compose.runtime.getValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import androidx.health.connect.client.PermissionController
import net.softavis.healthhub.pairing.QrScannerScreen
import java.time.ZoneId
import java.time.format.DateTimeFormatter

@Composable
fun HealthHubApp(
    viewModel: HealthHubViewModel,
) {
    val state by viewModel.uiState.collectAsState()

    val permissionsLauncher =
        rememberLauncherForActivityResult(
            contract = PermissionController
                .createRequestPermissionResultContract(),
        ) {
            viewModel.refreshPermissions()
        }

    LaunchedEffect(
        state.session,
        state.permissionsGranted,
    ) {
        if (
            state.session != null &&
            state.healthConnectAvailable &&
            !state.permissionsGranted
        ) {
            permissionsLauncher.launch(
                viewModel.healthConnectManager.permissions,
            )
        }
    }

    if (state.scanning) {
        QrScannerScreen(
            onQrCodeScanned = viewModel::handleQrCode,
        )

        return
    }

    Scaffold { padding ->
        MainContent(
            padding = padding,
            state = state,
            onPair = viewModel::startScanner,
            onRequestPermissions = {
                permissionsLauncher.launch(
                    viewModel.healthConnectManager.permissions,
                )
            },
            onSync = viewModel::sync,
            onDisconnect = viewModel::disconnect,
        )
    }
}

@Composable
private fun MainContent(
    padding: PaddingValues,
    state: HealthHubUiState,
    onPair: () -> Unit,
    onRequestPermissions: () -> Unit,
    onSync: () -> Unit,
    onDisconnect: () -> Unit,
) {
    Column(
        modifier = Modifier
            .fillMaxSize()
            .padding(padding)
            .padding(24.dp),
        verticalArrangement = Arrangement.spacedBy(16.dp),
    ) {
        Text(
            text = "Health Hub",
            style = MaterialTheme.typography.headlineLarge,
        )

        HorizontalDivider()

        if (state.session == null) {
            Text(
                text = "Not paired",
                style = MaterialTheme.typography.titleMedium,
            )

            Text(
                text = "Scan the QR code generated by Health Hub to connect this device.",
            )

            Button(
                modifier = Modifier.fillMaxWidth(),
                enabled = !state.pairing,
                onClick = onPair,
            ) {
                if (state.pairing) {
                    CircularProgressIndicator()
                } else {
                    Text("Pair device")
                }
            }
        } else {
            Text(
                text = "Connected ✔",
                style = MaterialTheme.typography.titleMedium,
            )

            LabelValue(
                label = "Backend",
                value = state.session.api,
            )

            LabelValue(
                label = "Health Connect",
                value = when {
                    !state.healthConnectAvailable ->
                        "Unavailable"

                    state.permissionsGranted ->
                        "Permissions granted ✔"

                    else ->
                        "Permissions required"
                },
            )

            LabelValue(
                label = "Last sync",
                value = state.lastSync?.let {
                    DATE_TIME_FORMATTER.format(
                        it.atZone(ZoneId.systemDefault()),
                    )
                } ?: "Never",
            )

            if (
                state.healthConnectAvailable &&
                !state.permissionsGranted
            ) {
                Button(
                    modifier = Modifier.fillMaxWidth(),
                    onClick = onRequestPermissions,
                ) {
                    Text("Grant permissions")
                }
            }

            Button(
                modifier = Modifier.fillMaxWidth(),
                enabled = state.permissionsGranted &&
                        !state.syncing,
                onClick = onSync,
            ) {
                if (state.syncing) {
                    CircularProgressIndicator()
                } else {
                    Text("Sync now")
                }
            }

            OutlinedButton(
                modifier = Modifier.fillMaxWidth(),
                enabled = !state.syncing,
                onClick = onDisconnect,
            ) {
                Text("Disconnect")
            }
        }

        state.message?.let { message ->
            Spacer(modifier = Modifier.height(8.dp))

            Text(
                text = message,
                color = MaterialTheme.colorScheme.primary,
            )
        }

        state.error?.let { error ->
            Spacer(modifier = Modifier.height(8.dp))

            Text(
                text = error,
                color = MaterialTheme.colorScheme.error,
            )
        }
    }
}

@Composable
private fun LabelValue(
    label: String,
    value: String,
) {
    Column(
        verticalArrangement = Arrangement.spacedBy(4.dp),
    ) {
        Text(
            text = label,
            style = MaterialTheme.typography.labelMedium,
        )

        Text(
            text = value,
            style = MaterialTheme.typography.bodyLarge,
        )
    }
}

private val DATE_TIME_FORMATTER =
    DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")